### ISSUE TITLE
Feature request: cover the cutout in voyager dock

### ISSUE THREAD

**Issue by viranch** [sondresj/scad-models#2]
Hi, would you be able to cover the cutout from the top (perhaps with a thin plate) so the palm wrist can stay from "falling in" while also maintaining the magnetic leg slots? Thanks!

**Comment by sondresj** [comment]
Hi! Sorry for the late reply @viranch . I've been really busy lately.

If I understand you correctly, I think it's doable, but would require printing with supports, as the overhang would be quite significant. 
Do you want it to be open under the keyboard? An alternative would be to just extend the wrist support to just under the keyboard, and leave a smaller square hole under the keyboard. The hole is there to reduce printing time and allow for some space to manage the connecting cable, so I'd keep some space there at least.

Also, feel free to copy the scad code and tinker with some modifications, it's quite easy to work with, even if it looks intimidating at first ;)

Let me know what you think, and if you're still interessted I'll find time to make the changes for you :)

**Comment by viranch** [comment]
> An alternative would be to just extend the wrist support to just under the keyboard, and leave a smaller square hole under the keyboard. The hole is there to reduce printing time and allow for some space to manage the connecting cable, so I'd keep some space there at least.

Yes that works perfectly for what I'm imagining I need! And makes sense for reducing printing time plus cable management.

> Also, feel free to copy the scad code and tinker with some modifications, it's quite easy to work with, even if it looks intimidating at first ;)
>
> Let me know what you think, and if you're still interessted I'll find time to make the changes for you :)

Yep never done it before, so definitely looks intimidating but I'll try to find time to give it a shot! I do appreciate any help you can provide too :)

**Comment by sondresj** [comment]
@viranch Added a version with a quick solution to cover the gap between the palm rest and keyboard, maintaining as much space as possible for cable management and print time reduction, hopefully this works for you, if not, please reopen the issue, or feel free to make changes to the code to suit your needs :) https://github.com/sondresj/scad-models/blob/main/voyager_dock/the_dock_no_gap.stl

**Comment by viranch** [comment]
Thank you very much!
